import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Web3, { EthExecutionAPI, SupportedProviders } from "web3";
import { Web3ContextInitOptions } from "web3-core";
import { RegisteredSubscription } from "web3-eth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  function getLibrary(provider: string | SupportedProviders<EthExecutionAPI> | Web3ContextInitOptions<EthExecutionAPI, RegisteredSubscription> | undefined) {
    return new Web3(provider)
  }

  return (
    <html lang="en">
      {/* <Web3ReactProvider getLibrary={getLibrary}> */}
        <body className={inter.className}>{children}</body>
      {/* </Web3ReactProvider > */}
    </html>
  );
}
